<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="mobile_robot_lidar" params="prefix">
    <!-- copy from robot macro -->
    <xacro:property name="bodylen" value="0.5461"/>
    <xacro:property name="lidarlen" value="0.1"/>
    <xacro:property name="lidarOZ" value="-0.03"/>
    <!-- add a simulated lidar, including visual, collision and inertial properties, and physics simulation-->
    <link name="lidar_link">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://simple_mobile_robot/mesh/sick_lms-200.stl"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://simple_mobile_robot/mesh/sick_lms-200.stl"/>
        </geometry>
        <!-- <material name="">
          <color rgba="0.7 0.8 0.9 1"/>
        </material> -->
      </visual>

      <inertial>
        <mass value="0.160"/>
        <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>

    <joint name="lidar_joint" type="fixed">
      <axis xyz="0 1 0"/>
      <origin xyz="${bodylen/2+lidarlen} 0 ${lidarOZ}" rpy="0 0 0"/>
      <parent link="robot_body"/>
      <child link="lidar_link"/>
    </joint>
    <!-- here is the gazebo plug-in to simulate a lidar sensor -->
    <gazebo reference="lidar_link">
      <sensor type="gpu_ray" name="sick_lidar">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>30</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>200</samples>
              <resolution>1</resolution>
              <min_angle>-1.570796</min_angle>
              <max_angle>1.570796</max_angle>
            </horizontal>
          </scan>
          <resolution>0.001</resolution>
          <range>
            <min>0.10</min>
            <max>60.0</max>
            <resolution>0.001</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.001</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_lidar_controller" filename="libgazebo_ros_gpu_laser.so">
          <topicName>/scan</topicName>
          <frameName>lidar_link</frameName>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>
