topics:
-
  name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 10
-
  name    : keyboard
  topic   : key_vel
  timeout : 0.5
  priority: 30
-
  name    : rqt
  topic   : rqt_vel
  timeout : 0.5
  priority: 30
locks:
-
  name    : lidar_estop
  topic   : lidar_alarm
  timeout : 0.2
  priority: 100
